### ISSUE TITLE
"UNKNOWN:Error received from peer with specific metrics

### ISSUE THREAD

**Issue by bpc80** [frequenz-floss/frequenz-client-reporting-python#110]
### What happened?

Hello,

When I try to retrieve certain metrics, I get the following errors. Other metrics work. I am using the current 0.9.0 version

Ex: AC_ACTIVE_POWER, AC_REACTIVE_POWER work

This one does not AC_ACTIVE_ENERGY_CONSUMED,AC_ACTIVE_ENERGY

Error message I get are: 
RPC failed: <AioRpcError of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Internal server error"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Internal server error", grpc_status:13, created_time:"2024-11-13T13:31:53.864517656+00:00"}"

### What did you expect instead?

I expect the current meter reading when I call it up

### Affected version(s)

0.9.0

**Comment by cwasicki** [comment]
Hello, thanks for reporting the issue. This should be fixed when using the latest version of the client >=v0.11 and a new service instance. We will send an update on this soon.

**Comment by bpc80** [comment]
Hello,

I have just installed 0.11. Still the same message.  I tried  AC_ACTIVE_ENERGY_CONSUMED as wall as AC_ACTIVE_ENERGY. 

Still get:

```
RPC failed: <AioRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Invalid argument in request"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Invalid argument in request", grpc_status:3, created_time:"2024-11-28T07:27:37.413225059+00:00"}"
>
microgrid_id: XXX, component_id: XXX, Anzahl der erhaltenen Datensätze: 0
Empty DataFrame
Columns: []
Index: []
```

frequenz-api-common       0.6.3
frequenz-api-reporting    0.5.0
frequenz-channels         1.3.0
frequenz-client-base      0.8.1
frequenz-client-common    0.2.0
frequenz-client-reporting 0.11.0


Here my code. Maybe something is wrong here?

I have replaced the apikey, microgrid_id and component_id with xxx to avoid posting sensitive information publicly.

```
import pandas as pd
from datetime import datetime, timedelta
import asyncio
from frequenz.client.common.metric import Metric
from frequenz.client.reporting import ReportingApiClient
import pytz

# Parameter für den Test
metric_str = "AC_ACTIVE_ENERGY_CONSUMED"
component_id = XXX  # component_id als Integer definiert
microgrid_id = XXX  # microgrid_id als Integer definiert
resolution = 300

# Initialisiere den ReportingApiClient
client = ReportingApiClient(server_url="grpc://reporting.api.frequenz.com:443?ssl=true", key="XXX")

# Dynamische Zeitfenster - Letzte 2 Tage
end_dt = datetime.now()
start_dt = end_dt - timedelta(days=2)

data_list = []

# Konvertiere den Metric-String in eine Liste von Metric-Objekten
metrics = []
for metric in metric_str.split(','):
    metric = metric.strip()
    if hasattr(Metric, metric):
        metrics.append(getattr(Metric, metric))
    else:
        print(f"Warnung: Ungültiger Metric-Name '{metric}' f  r microgrid_id {microgrid_id}, component_id {component_id}")

async def fetch_data():
    if metrics:
        data_sample = [
            sample async for sample in client.list_single_component_data(
                microgrid_id=microgrid_id,
                component_id=component_id,
                metrics=metrics,
                start_dt=start_dt,
                end_dt=end_dt,
                resampling_period=timedelta(seconds=resolution)
            )
        ]
        data_list.extend(data_sample)
    else:
        print(f"Warnung: Keine gültigen Metriken für microgrid_id {microgrid_id}, component_id {component_id}")
        
        
loop = asyncio.get_event_loop()
loop.run_until_complete(fetch_data())

# Ausgabe der Anzahl der erhaltenen Datens  tze
print(f"microgrid_id: {microgrid_id}, component_id: {component_id}, Anzahl der erhaltenen Datensätze: {len(data_list)}")
```

**Comment by cwasicki** [comment]
Hello, the latest version of the client only works with the latest deployment of the service, which is not available under that address. Carsten will send you the address of the new service instance soon.

**Comment by bpc80** [comment]
Hello, i wait for the new service address? Do you have one for me?

**Comment by cwasicki** [comment]
Followed up by mail, can we close this?

**Comment by bpc80** [comment]
Hello,

you can close it.
